import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/1.jpg',
    title: 'Parallel Bible Books1',
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/courses/2.jpg',
    title: 'Parallel Bible Books2',
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/courses/3.jpg',
    title: 'Parallel Bible Books3',
    rating: 4,
    ratingCount: 7,
    price: 30,
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/courses/4.jpg',
    title: 'Parallel Bible Books4',
    rating: 4,
    ratingCount: 12,
    price: 30,
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/courses/5.jpg',
    title: 'Parallel Bible Books5',
    rating: 4,
    ratingCount: 32,
    price: 35,
    category: 'Intermediate',
  },
  {
    id: 6,
    cover: '/images/courses/6.jpg',
    title: 'Parallel Bible Books6',
    rating: 5,
    ratingCount: 14,
    price: 35,
    category: 'Beginner',
  },
  {
    id: 7,
    cover: '/images/courses/7.jpg',
    title: 'Parallel Bible Books7',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
  },
]
