import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/books/book1.png',
    title: 'BOOK OF RUTH',
    rating: 5,
    ratingCount: 8,
    price: 0,
    level: 'Free',
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/books/book2.jpg',
    title: 'EPISTLE OF THE APOSTLE PAUL TO THE GALATIANS',
    rating: 5,
    ratingCount: 15,
    price: 0,
    level: 'Free',
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/books/book3.jpg',
    title: 'BOOK OF THE PROPHET JONAH',
    rating: 4,
    ratingCount: 7,
    price: 0,
    level: 'Free',
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/books/book4.jpg',
    title: '1 EPISTLE OF THE APOSTLE PAUL TO TIMOTHY',
    rating: 4,
    ratingCount: 12,
    price: 0,
    level: 'Free',
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/books/book5.jpg',
    title: 'BOOK OF THE PROPHET ZECHARIAH',
    rating: 4,
    ratingCount: 32,
    price: 0,
    level: 'Free',
    category: 'Intermediate',
  },
  {
    id: 6,
    cover: '/images/books/book6.jpg',
    title: 'BOOK OF THE PROPHET MALACHI',
    rating: 5,
    ratingCount: 14,
    price: 0,
    level: 'Free',
    category: 'Beginner',
  },
  {
    id: 7,
    cover: '/images/books/book7.jpg',
    title: 'EPISTLES OF THE APOSTLE JOHN',
    rating: 4,
    ratingCount: 6,
    price: 25,
    level: 'Paid Books',
    category: 'Beginner',
  },
  {
    id: 8,
    cover: '/images/books/book8.jpg',
    title: 'EPISTLES OF THE APOSTLE PETER',
    rating: 4,
    ratingCount: 6,
    price: 25,
    level: 'Paid Books',
    category: 'Beginner',
  },
  {
    id: 9,
    cover: '/images/books/book9.jpg',
    title: 'EPISTLE OF THE APOSTLE PAUL TO TITUS',
    rating: 4,
    ratingCount: 6,
    price: 20,
    level: 'Paid Books',
    category: 'Beginner',
  },
  {
    id: 10,
    cover: '/images/books/book10.jpg',
    title: 'EPISTLE OF THE APOSTLE PAUL TO ROMANS',
    rating: 4,
    ratingCount: 6,
    price: 20,
    level: 'Paid Books',
    category: 'Beginner',
  },
  {
    id: 11,
    cover: '/images/books/book11.jpg',
    title: 'EPISTLE OF THE APOSTLE JAMES',
    rating: 4,
    ratingCount: 6,
    price: 25,
    level: 'Paid Books',
    category: 'Beginner',
  },
  {
    id: 12,
    cover: '/images/books/book12.jpg',
    title: 'THE GOSPEL ACCORDING TO MATTHEW',
    rating: 4,
    ratingCount: 6,
    price: 20,
    level: 'Paid Books',
    category: 'Beginner',
  },
  {
    id: 13,
    cover: '/images/books/book13.jpg',
    title: 'BOOK OF GENESIS',
    rating: 4,
    ratingCount: 6,
    price: 30,
    level: 'Paid Books',
    category: 'Beginner',
  },
  {
    id: 14,
    cover: '/images/books/book14.jpg',
    title: 'BOOK OF THE PROPHET DANIEL',
    rating: 4,
    ratingCount: 6,
    price: 30,
    level: 'Paid Books',
    category: 'Beginner',
  },
]
